#!/bin/bash

function bgp {
  api='https://api.bgpview.io/' query="$1" term="$2"

  [ -z $query ] && {
    echo "usage: "
    echo "\`/bgp <IP/IPv6>\` IP/IPv6 info"
    echo "\`/bgp <ASxxx>\` AS info"
    echo "\`/bgp peer <ASxxx>\` AS peer list"
    echo "\`/bgp prefix <ASxxx>\` AS prefix list"
    echo "\`/bgp <desc>\` lookup ASN/Prefixes by desc/name"
    exit 1
  }

  [[ $query =~ ^(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))$ ]] && act=ip verb=ip/$query 
  [[ $query =~ ^((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])$ ]] && act=ip verb=ip/$query
  [[ $query == "peer" ]] && act=peer verb=asn/$query/peers
  [[ $query == "prefix" ]] && act=prefix verb=asn/$query/prefixes
  [[ $query =~ ^AS[0-9]* ]] && act=asn verb=asn/$(tr -d '[:alpha:]' <<< "$query")
  [ -z $act ] && act=search verb="search?query_term=$query"

  curl -s --max-time 5 "$api$verb" | {
    res="$(cat)"
    [ -z "$res" ] && echo "Error looking up: Empty Respond." && exit 1
    jq -r '.status' <<< "$res" | {
      read status
      [ $status != ok ] && echo "Error looking up: API returned error." && exit 1
    }
    jq -rc '.data' <<< "$res" | {
      case $act in
        asn) 
          jq -cr '.asn, .name, .description_short, .country_code' | {
            read asn; read name; read desc; read cc
	    echo "[AS${asn}](https://bgpview.io/asn/${asn}) *${name}* _${desc}_ (${cc})"
	    echo -n "*Prefixes*: "
	    curl -s --max-time 5 "$api/asn/$asn/prefixes/" | \
              jq -cr '.data | .ipv4_prefixes, .ipv6_prefixes | .[] | .prefix' | \
              head -n20 | while read p; do {
                echo -n "[$p](https://bgpview.io/prefix/$p), "
              }; done | sed -e 's/, $/ .../;'
	    echo && echo -n "*Peers*: "
	    curl -s --max-time 5 "$api/asn/$asn/peers/" | \
              jq -cr '.data | .ipv4_peers, .ipv6_peers | .[] | .asn' | \
              sort | uniq | head -n70 | while read a; do {
                echo -n "[AS$a](https://bgpview.io/asn/$a), "
              }; done | sed -e 's/, $/ .../;'
          }
        ;;
        prefix)
          jq -cr '.ipv4_prefixes, .ipv6_prefixes | 
                  .[] | 
                  .prefix, .name, .description, .country_code' \
            | while read prefix; do {
              read name; read desc; read cc
	      echo "[${prefix}](https://bgpview.io/prefix/${prefix}) *${name}* _${desc}_ (${cc})"
            }; done
        ;;
        peer)
          jq -cr '.ipv4_peers, .ipv6_peers' | {
            read v4; read v6
            for ptr in v4 v6; do {
              eval "data=\$$ptr"
              jq -cr '.[] | .asn, .name, .description, .country_code' <<< "$data" | \
              while read asn; do {
                read name; read desc; read cc
		echo "[AS${asn}](https://bgpview.io/asn/${asn}) *${name}* _${desc}_ (${cc}) IP${ptr}"
              }; done
            }; done
          }
        ;;
        ip) 
          jq -cr '.ip, .ptr_record, .prefixes' | while read ip; do {
            read ptr; read pfx
            echo "\`$ip\` ($ptr)"
            jq -cr '.[] | .prefix, .name, .description, .country_code, .asn .asn, .asn .description' <<< "$pfx" | \
            while read prefix; do {
              read name; read desc; read cc; read asn; read as_desc;
	      echo "[${prefix}](https://bgpview.io/prefix/${prefix}) *${name}* _${desc}_ ($cc) from [AS${asn}](https://bgpview.io/asn/${asn}) (_${as_desc}_)"
            }; done
          }; done 
        ;;
        search)
          jq -cr '.asns, .ipv4_prefixes, .ipv6_prefixes' | {
            read asns; read ip4; read ip6
            echo -n "*ASNs*: "
            jq -cr '.[] | .asn, .name' <<< "$asns" | head -n90 | while read asn; do {
              read name
              echo -n "[AS${asn}](https://bgpview.io/asn/${asn}) *${name}*, "
            }; done | sed -e 's/, $/ .../;'
            echo && echo -n "*Prefixes*: "
            jq -cr '.[] | .prefix, .name' <<< "$ip4 $ip6" | head -n90 | while read prefix; do {
              read name
              [ -z $name ] && name=null
              echo -n "[${prefix}](https://bgpview.io/prefix/${prefix}) *${name}*, "
            }; done | sed -e 's/, $/ .../;'
          }
        ;;
      esac
    }
  } 
}
